features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: true
  favicon: false
logo:
  use_default: true
  path: ''
favicon:
  use_default: false
  path: ''
  mimetype: image/vnd.microsoft.icon
